#服务器端口
server:
  port: 8280
  servlet:
    context-path: /projectdevmanage

#druid数据源配置
spring:
  datasource:
    #通过这句配置将druid连接池引入到我们的配置中，spring会尽可能判断类型是什么，然后根据情况去匹配驱动类。
    #    type: com.alibaba.druid.pool.DruidDataSource
    ##动态数据源配置
    #    url: jdbc:p6spy:mysql://127.0.0.1:3306/cloudoa?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/shenhaocloud?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2b8&zeroDateTimeBehavior=CONVERT_TO_NULL&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver  # mysql8.0以前使用com.mysql.jdbc.Driver
    username: root
    password: root
    druid:
      initial-size: 5  # 初始化大小
      min-idle: 5  # 最小
      max-active: 100  # 最大
      max-wait: 60000  # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      validationQuery: select 'x'
      test-while-idle: true  # 当连接空闲时，是否执行连接测试
      test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
      test-on-return: false  # 在连接归还到连接池时是否测试该连接
      filters: config,wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=false
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      #WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true #是否启用StatFilter默认值true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      #StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true #是否启用StatViewServlet默认值true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
    #  redis:
    #    #数据库索引
    #    database: 7
    #    host: 127.0.0.1
    #    port: 6379
    #    password: 123456
    #    #连接超时时间
    #    timeout: 5000
    #    lettuce:
    #      pool:
    #        max-active: 32
    #        max-wait: 300
    #        max-idle: 16
    #        min-idle: 8
    #    jedis:
    #      pool:
    #        max-active: 32
    #        max-wait: 300
    #        max-idle: 16
    #        min-idle: 8
    #  activiti:
    #    database-schema-update: true
    #    check-process-definitions: false
    #    # 开启历史库 这样在启动项目建表时会新建25张表，包含历史表，否则只会新建18张表，无法使用##  历史表，像批注之类的也就无法操作，会报错
    #    db-history-used: true
    #    history-level: audit
    #    #流程定义文件存放目录4
    #    process-definition-location-prefix: classpath:/processes/
    #    # 启用作业执行器
    #    async-executor-activate: false
    #数据库版本管理
    #  flyway:
    #    # 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
    #    enabled: true
    #    # 如果数据库不是空表，需要设置成 true，否则启动报错
    #    baseline-on-migrate: true
    #    # 验证错误时 是否自动清除数据库 高危操作!
    #    clean-on-validation-error: false
    #    # 脚本位置
    #    locations: classpath:db/migration
    #    # 编码格式，默认UTF-8
    #    encoding: UTF-8

#日志配置

#token过期时间
#token:
#  expire: 720
#
##禅道地址前缀
#candao:
#  url: http://106.14.42.15:82/zentao/bug-view-%s.html

#mybatis-plus
mybatis-plus:
  configuration:
    #开启驼峰user_name->userName
    map-underscore-to-camel-case: true
    #自动映射任意复杂的结果集
    auto-mapping-behavior: full
    #是否开启二级缓存
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #对应mapper文件
  mapper-locations: classpath*:/mapper/*Mapper.xml,org/jeecg/modules/**/xml/*Mapper.xml

  global-config:
    # 逻辑删除配置
    db-config:
      logic-delete-field: deleted
#        # 删除前
#        logic-not-delete-value: 0
#        # 删除后
#        logic-delete-value: 1

#jwt
#jwt:
#  header: Authorization
#  # 令牌前缀
#  token-start-with: Bearer
#  # 必须使用最少88位的Base64对该令牌进行编码
#  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
#  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成
#  token-validity-in-seconds: 14400000
#  # 在线用户key
#  online-key: onlinetoken
#  # 验证码
#  code-key: codekey
#
##登录图形验证码有效时间/分钟
#loginCode:
#  expiration: 2
#
## 是否限制单用户登录
#single:
#  login: false